services:
  publisher:
    build: ./cmd_publisher
    privileged: true
    volumes:
      - /dev/input:/dev/input
      - ${LOG_DIR:-./logs}:/logs
    ports:
      - "${ZMQ_PORT:-5580}:${ZMQ_PORT:-5580}"
      - "${CONTROL_PORT:-5581}:${CONTROL_PORT:-5581}"
    environment:
      - ZMQ_HOST=${ZMQ_HOST:-"*"}
      - ZMQ_PORT=${ZMQ_PORT:-5580}
      - CONTROL_PORT=${CONTROL_PORT:-5581}
      - LOG_DIR=/logs
      - DEVICE_VID=${DEVICE_VID:-c001}
      - DEVICE_PID=${DEVICE_PID:-1dea}
      - SESSION_ID=${SESSION_ID:-}
    restart: unless-stopped
